### ISSUE TITLE
Failing when spaces in project directory path.

### ISSUE THREAD

**Issue by wcatron** [Gert-dev/php-integrator-autocomplete-plus#24]

**Comment by Gert-dev** [comment]
I recall you created a patch for the base package related to this. Can you confirm this is fixed?

**Comment by wcatron** [comment]
I can confirm that yes.

https://github.com/Gert-dev/php-integrator-base/pull/35

-Weston

**Comment by Gert-dev** [comment]
Ok, thanks :+1: .
