### ISSUE TITLE
Array autocomplete

### ISSUE THREAD

**Issue by brainfoolong** [Gert-dev/php-integrator-autocomplete-plus#33]
In my currently favorite editor apart from Atom i have autocompletion also available for arrays which is really helpful.

For example a can do something like this and the autocompletion works.
Do you have plans to integrate something like this?

	class MyClass{
		public $hello;
	}

	/**
	*
	* @return MyClass[]
	*/
	function getMyClasses(){

	}

	$classes = getMyClasses();

	foreach($classes as $myClassInstance){
		$myClassInstance->hell...
	}

**Comment by Gert-dev** [comment]
Yes, I do have plans to add something like this sooner or later. I'll mark this as enhancement.

**Comment by Gert-dev** [comment]
Hello again, this actually belongs in the base package. I've implemented it there and it will be part of upcoming release 0.5.0!
