### ISSUE TITLE
Allow disabling automatic import statements.

### ISSUE THREAD

**Issue by Gert-dev** [Gert-dev/php-integrator-autocomplete-plus#34]
See also [1].

[1] https://github.com/Gert-dev/php-integrator-base/issues/55

**Comment by pascalchevrel** [comment]
The addition of use statements is useless for calls to classes *in the same namespace* it just adds useless noise to the file that I have to delete manually. I was wondering which package was adding all this noise to my files.

Additionally, it's not clever, if I start adding a call to a method from another class somewhere in the class but change my mind and delete this code, autocomplete-plus does  not remove  the use statement at the top of the file even though I don't need it.

It also does not respect the PSR standard of keeping a blank line between the namespace and the use statement.

**Comment by Gert-dev** [comment]
Hello

This ticket is not about adding use statements in the same namespace, it is about adding an option to always complete the FQCN and never add use statements and complete the short name.

I tend to agree with you that adding use statements for classes for classes from the same namespace is unnecessary. In fact, I also raised this issue in the atom-autocomplete-php package [1]. However, as the author also indicates, the use statements might no longer be "just clutter" when you decide to move the class to a new namespace. This is a valid point. Whichever the case, adding an option so you as end-user can decide which behavior you want is also taken up in this ticket [2].

Finally, having lingering use statements if you delete code is going to happen even if classes from the same namespace aren't imported. In other words, it will only fix the problem for classes in the same namespace, but you will still have that problem for classes from other namespaces. I also don't think it's autocomplete-plus' responsibility to be deleting them again (perhaps it's also not its responsibility to be adding them at all). IIRC IDE's like PHPStorm also don't automatically remove them again, but they do mark them as 'unused' (would be interesting to add this in a linter-like package). A refactoring package could also automatically replace all the use statements with something else if you decide to rename a class.

[1] https://github.com/Peekmo/atom-autocomplete-php/issues/64
[2] https://github.com/Gert-dev/php-integrator-autocomplete-plus/issues/6

**Comment by Gert-dev** [comment]
Closing in favor of #48.
