### ISSUE TITLE
Autocomplete for multi-folder project

### ISSUE THREAD

**Issue by hultberg** [Gert-dev/php-integrator-autocomplete-plus#40]
When developing I have a library as a second project folder. It's quite large and I would love autocomplete on it's classes. A feature for autocomplete in other projectfolders would be great! :smile:

**Comment by Gert-dev** [comment]
Hello. Thanks for reporting this, it will (should) automatically be supported as soon as the base package gains support for it. You can track progress on it in [1].

[1] https://github.com/Gert-dev/php-integrator-base/issues/81

**Comment by hultberg** [comment]
I think php-integrator is unable to process the library I want autocomplete for, because of Gert-dev/php-integrator-linter#11

**Comment by hultberg** [comment]
Forget my comment over.

@Gert-dev; I would love this to be implement in the near future.

**Comment by Gert-dev** [comment]
Closing this as it's now (or should be) fixed.
