### ISSUE TITLE
use statements

### ISSUE THREAD

**Issue by hultberg** [Gert-dev/php-integrator-autocomplete-plus#48]
I have a project that does not utilise namespaces and has custom autoloaders. When I choose a suggested class – that the package suggested – an `use` statement is added, regardless if the suggested class has a declared namespace.

**Comment by tellkonkle** [comment]
I'm having the same issue. Please allow us to disable the automatic use statements.

**Comment by Gert-dev** [comment]
Sorry, there are just so many issues and things to do in all of the integrator packages that I sometimes lose track of the low hanging fruit. On a more positive node, I've just added this and it will be available in the next release!

**Comment by tellkonkle** [comment]
Thank you! I donated a few "coffee beans" to last night. It's so refreshing to finally have a non-IDE editor with some halfway "intellisense" for PHP. Most of the time Atom, Brackets, Sublime, etc. packages are a bit messy and dysfunctional. I'm still shocked how well your packages work and how clean the source actually is. Keep up the good work! I'm sure I'll be sending some more coffee beans your way!

**Comment by Gert-dev** [comment]
Thanks for your kind words, glad to be of service!
