### ISSUE TITLE
Autocomplete dropdown display issues

### ISSUE THREAD

**Issue by bgdxv** [Gert-dev/php-integrator-autocomplete-plus#53]
As it can be observed in the screenshot, the dropdown created by the package has some weird spacing in front of the actual autocomplete and it also goes under the tree view package on the left.
![issue](https://cloud.githubusercontent.com/assets/7222648/15448880/db072aac-1f76-11e6-8213-f637cb005f95.png)

I want to thank you for the wonderful work that you are doing with these packages!

**Comment by Gert-dev** [comment]
Thanks for the compliment! Do you happen to be using a custom UI theme? The autocomplete popup nicely overlays the tree view whenever it needs the space on my installation.

**Comment by bgdxv** [comment]
No, I am using the default One Dark theme.

**Comment by Gert-dev** [comment]
Ok, this sounds like a bug in the autocomplete-plus package. This package only supplies the actual suggestions that are displayed in the list, but does not manage the actual overlay or perform additional styling to it. It is probably best to report it there (I took a quick gander and don't see any similar open issues reported).

[1] https://github.com/atom/autocomplete-plus/issues

**Comment by bgdxv** [comment]
So I looked a bit deeper into that package's issues and found it :)
https://github.com/atom/autocomplete-plus/issues/704

**Comment by Gert-dev** [comment]
Alright, I'll close this one since it's actually a bug somewhere else. Thanks for reporting it :-).
