### ISSUE TITLE
Feature: Service Injection Autocompletion

### ISSUE THREAD

**Issue by cabloo** [Gert-dev/php-integrator-autocomplete-plus#55]
I have yet to find an Atom package for this, and it may be out of the scope of this package (i.e. should be added to another `php-integrator` package), but I was really hoping for a package that would automate Service Injection as much as possible for me.

For those unfamiliar, almost every start of a class in my project looks something like this:

```php
class TargetFinder
{
    /**
     * @var FormatService
     */
    protected $format;

    /**
     * @var RtgRouterRepository
     */
    protected $routers;

    /**
     * @var RtgInterfaceRepository
     */
    protected $targets;

    public function __construct(
        FormatService $format,
        RtgRouterRepository $routers,
        RtgInterfaceRepository $targets
    ) {
        $this->format = $format;
        $this->routers = $routers;
        $this->targets = $targets;
    }

    // Implementation...
}
```

Laravel detects and injects (resolves an instance of and passes as an argument) each of those variables required by the constructor. I find myself typing most of that out, which is quite inefficient. I have snippets for the doc blocks and usually use multi-copy-paste but that still is not quick enough for me.

I think ideal functionality for me would be a command I run that asks for the name of the variable and the class name (auto-completed), but another thing that could work is when typing in a function I could `ctrl-shift-click` (or similar) on a class variable that does not exist yet and it would request a class name to auto inject for it. For instance, if I were in the above class, and I decided I needed a Cache implementation, I could type

```php
function find($id)
{
    return $this->cache->get('targets.'.$id, function () use ($id) {
        // resolve from database
    });
}
```

And since cache isn't a class variable I could trigger a special click on it that asks what class and adds it above, i.e. if I typed `Cache` it would `use` the right `Cache` and then add it to the constructor and add the protected variable with a doc block. Since this would only occur if `$this->cache` was not found as a variable, maybe it would be the same command as the `php-integrator-navigator` package (`ctrl-alt-click`), since navigator would essentially be saying "I don't know where this variable is, do you want to inject one?"

**Comment by cabloo** [comment]
This is a Sublime command which seems to do something similar to what I'm trying to achieve above:

https://github.com/erichard/SublimePHPCompanion/blob/master/php_companion/commands/insert_php_constructor_property.py

**Comment by Gert-dev** [comment]
Sounds like a task for the [refactoring](https://github.com/Gert-dev/php-integrator-refactoring) package. I was (and still partially am) facing the same repetitive tasks with dependency injection and added some features there that will (hopefully) at least mitigate your problem a bit:
* Type out a class property (without docblock).
* Put your cursor inside it, press alt-enter and select `Generate Docblock`.
* Update the `@var` tag.
* Once you've completed most or your class or wish to update the constructor, press alt-enter inside the class and select `Generate Constructor`.

I understand it is not as convenient as what you're looking for, but it might help you until such a functionality arrives. Would you mind moving this ticket to the refactoring package?

**Comment by cabloo** [comment]
Ah, that is definitely on the right track, thank you for pointing me to that feature. I will move this ticket to that package.
