### ISSUE TITLE
Autocomplete does not see methods inside functions.php (wordpress)

### ISSUE THREAD

**Issue by maximumver** [Gert-dev/php-integrator-autocomplete-plus#57]
Example:

I have a .php file with some my methods/functions. **upd: not a class**
I am creating one more method and inside of this method i do these steps:

I am creating a variable:

$conn;

Want to assign a <s>class</s>method that returns a connection.

$conn = DBconnect();

But autocomplete doesn't see my own **upd.**<s>class.</s> methods name.
So i am writing it manually.
Why so?

**Comment by Gert-dev** [comment]
Is the class namespaced? If so, is the proper use statement present at the top of the file (if not, the class name must be fully qualified).

**Comment by maximumver** [comment]
I'm sorry. I'm not really a developer. Didn't tell very important detail.
I'm editing a wordpress file - functions.php file
It doesn't have any classes inside, only functions & variables.

Like this. 
<?php

function DBconnect() {
...
}
function B() {
...
}
function C() {
$conn = DBconnect();
.....
}

?>

**Comment by maximumver** [comment]
So its more like there is a file with a number of functions & variables inside, its not a class.
And when inside such file i am trying to assign one of those functions to some variable autocomplete doesn't see those methods. Default autocomplete see them i believe, but yours has more features :)

**Comment by Gert-dev** [comment]
There was a bug where only global function names with lower case letters were being recognized. I've released 1.0.2 of this package, could you give it a try and see if it helps?

**Comment by maximumver** [comment]
Yes, thank you!

**Comment by Gert-dev** [comment]
Great! Let me know if you experience any other issues.
