### ISSUE TITLE
Missing @inheritdoc for phpdoc autocomplete

### ISSUE THREAD

**Issue by squio** [Gert-dev/php-integrator-autocomplete-plus#62]
The fig-standards [PSR-5](https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md) propose the annotation [@inheritdoc](https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md#61-making-inheritance-explicit-using-the-inheritdoc-tag).

This tag is currently missing from php-integrator-autocomplete-plus.

**Comment by Gert-dev** [comment]
Merged, thanks for your contribution!
